const path = {
    HomeActive: require('../res/image/HomeActive.png'),
    BookingActive: require('../res/image/BookingActive.png'),
    HelpActive: require('../res/image/HelpActive.png'),
    MoreActive: require('../res/image/MoreActive.png'),
    HomeInactive: require('../res/image/HomeInactive.png'),
    BookingInactive: require('../res/image/BookingInactive.png'),
    HelpInactive: require('../res/image/HelpInactive.png'),
    MoreInactive: require('../res/image/MoreInactive.png'),

    otpIcon: require('../res/image/otpIcon.png'),
    nextArrow: require('../res/image/nextArrow.png'),
    logoTitle: require('../res/image/logoTitle.png'),
    appLogo: require('../res/image/appLogo.png'),
    downArrow: require('../res/image/downArrow.png'),
    google: require('../res/image/google.png'),
    fb: require('../res/image/fb.png'),
    waybusWhiteLogo: require('../res/image/waybusWhiteLogo.png'),
    twoPin: require('../res/image/twoPin.png'),
    sleeper: require('../res/image/sleeper.png'),
    seater: require('../res/image/seater.png'),
    notification: require('../res/image/notification.png'),
    nonAc: require('../res/image/nonAc.png'),
    mapPin: require('../res/image/mapPin.png'),
    ac: require('../res/image/ac.png'),
    search: require('../res/image/search.png'),
    calendar: require('../res/image/calendar.png'),
    rightTickIcon: require('../res/image/rightTickIcon.png'),
    closeIcon: require('../res/image/closeIcon.png'),
    
    profile: require('../res/image/profile.png'),
    wallet: require('../res/image/wallet.png'),
    card: require('../res/image/card.png'),
    dollor: require('../res/image/dollor.png'),
    help: require('../res/image/help.png'),
    settings: require('../res/image/settings.png'),
    about: require('../res/image/about.png'),
    logout: require('../res/image/logout.png'),
    Wbus: require('../res/image/Wbus.png'),
    rightArrow: require('../res/image/rightArrow.png'),
    busIcon: require('../res/image/busIcon.png'),
    confirmIcon: require('../res/image/confirmIcon.png'),
    downArrowIcon: require('../res/image/downArrowIcon.png'),
    confirmed: require('../res/image/confirmed.png'),
    mail: require('../res/image/mail.png'),
    smartphone: require('../res/image/smartphone.png'),
    headphone: require('../res/image/headphone.png'),
    upArrow: require('../res/image/upArrow.png'),
    cancelled: require('../res/image/cancelled.png'),
    offer: require('../res/image/offer.png'),

    leftArrow: require('../res/image/leftArrow.png'),
    backButton: require('../res/image/backButton.png'),
    polygon: require('../res/image/polygon.png'),
    vector: require('../res/image/vector.png'),

    seatWhite: require('../res/image/seatWhite.png'),
    seatGray: require('../res/image/seatGray.png'),
    seatPink: require('../res/image/seatPink.png'),
    upperWhiteSeat: require('../res/image/upperWhiteSeat.png'),
    upperPinkSeat: require('../res/image/upperPinkSeat.png'),
    upperBlueSeat: require('../res/image/upperBlueSeat.png'),
    upperGraySeat: require('../res/image/upperGraySeat.png'),
    success: require('../res/image/success.png'),
    bus_dark: require('../res/image/bus_dark.png'),

    twitter: require('../res/image/twitter.png'),
    walletGroup: require('../res/image/wallet-group.png'),
    walletOutline: require('../res/image/wallet-outline.png'),
    whatsapp: require('../res/image/whatsapp.png'),
    paypal: require('../res/image/paypal.png'),
    visa: require('../res/image/visa.png'),
    plus: require('../res/image/plus.png'),
    dropDownArrow: require('../res/image/dropDownArrow.png'),
    user: require('../res/image/user.png'),
    edit: require('../res/image/edit.png'),
    cancel: require('../res/image/cancel.png'),
    checked: require('../res/image/checked.png'),
    unchecked: require('../res/image/unchecked.png'),
    arrowRight: require('../res/image/arrowRight.png'),
    locationFrom: require('../res/image/locationFrom.png'),
    eyeOff: require('../res/image/eye-off.png'),
    whiteArrowDown: require('../res/image/whiteArrowDown.png'),
    sort: require('../res/image/sort.png'),
}
export default path;