import React, { Component } from 'react';
import { View, Text, Image, TouchableOpacity, FlatList, Switch } from 'react-native';
import { Images, Colors } from '../../../../theme';
import styles from './styles'
import { hp, wp } from '../../../../utils/heightWidthRatio';

export default class Wallet extends Component {
  constructor(props) {
    super(props);
    this.state = {
      view : [1],
    };
  }

  render() {
    const { view } = this.state
    return (
      <View style={styles.mainContainer}>

        <View style={styles.container}>
          <View style={styles.headerView}>
            <View style={{flexDirection : 'row', alignItems:'center'}}>
              <TouchableOpacity onPress={()=>this.props.navigation.goBack()} style={styles.centerView}>
                <Image style={[styles.smallIcon, {marginLeft:0}]} source={Images.backButton} />
              </TouchableOpacity>
              <Text style={styles.title}>About Us</Text>
            </View>  
            <TouchableOpacity onPress={() => this.props.navigation.navigate('notification')}>
              <Image style={styles.backIcon} source={Images.notification} />
            </TouchableOpacity>
          </View>
        </View>
        <View style={styles.locationContainer}>
          <View style={{flex:1}}>

            <FlatList
              data={view}
              showsVerticalScrollIndicator = {false}
              renderItem={({ item, index}) => (
                <View>

                  <Text style={styles.titleBlack}>Terms & Conditions</Text>
                  
                  <Text style={styles.grayContent}>
                    These terms and conditions (collectively, hereinafter referred to as the "Terms") govern your ("User") access to and use of the website, www.waybus.in and the WAYBUS mobile applications ("Website"). The Website is owned, managed and operated by WAYBUS.
                  </Text>
                  <Text style={styles.grayContent}>
                    Please read these Terms carefully before using the Website, which is an online marketplace. For the purpose of clarity, it is hereby stated that the Website is not engaged in providing any services by itself but is a platform, which merely connects the bus operators with the bus travellers.
                  </Text>
                  <Text style={styles.grayContent}>
                    These Terms are an electronic record in terms of the applicable legislation. This electronic record is generated by a computer system and does not require any physical or digital signatures. By using the Website, you signify your agreement to be bound by these Terms.
                  </Text>
                  <Text style={styles.grayContent}>
                    WAYBUS allows You to surf the Website or buy bus tickets for yourself, your family and your friends, without registering on the Website. You shall be deemed to have read, understood and expressly accepted these Terms, which shall govern the desired transaction of bus ticket booking through the Website for all purposes, and shall be binding on You. All Your rights and liabilities and/or the Website with respect to Your use of the Website and availing bus ticket booking facility ("Facility") provided by the Website shall be governed by these Terms.
                  </Text>
                  <Text style={styles.grayContent}>
                    PLEASE NOTE THAT YOUR USE OF THE WEBSITE IN ANY WAY SIGNIFIES YOUR ACCEPTANCE TO THE TERMS. By agreeing to these Terms, You also agree to WAYBUS' other Website policies; including but not limited to, (i) Privacy Policy, as amended from time to time; and (ii) Cookie Policy.
                  </Text>
                  <Text style={styles.grayContent}>
                    Both You and WAYBUS are individually referred to as 'Party' and collective referred to as 'Parties', in these Terms.
                  </Text>

                  <Text style={styles.blackContent}>
                    1. Terminology:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. Both You and WAYBUS are individually referred to as 'Party' and collective referred to as 'Parties', in these Terms.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. Both You and WAYBUS are individually referred to as 'Party' and collective referred to as 'Parties', in these Terms.
                    </Text>
                  </View>

                  <Text style={styles.blackContent}>
                    2. Our Website:
                  </Text>
                  <Text style={styles.grayContent}>
                    WAYBUS is an online Market Place, which gives prospective travelers and bus operators a platform to connect. In light of the foregoing, WAYBUS wishes to state the following:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. The Website is a marketplace, which merely lists the inventory of bus operators who are registered with the Website, but does not own the services per se. Hence, the limited role of the Website is to connect You with the bus operator and vice versa.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. You understand and agree that the fare of the bus tickets listed and/or offered for sale by the bus operator on the Website, is solely determined by the respective bus operator, and WAYBUS has no control over the fare of the tickets listed on the Website. In the event, the minimum and/or the maximum fare of the tickets, is in contravention of any law and/or any order or judgment of any regulatory authority/Tribunal/Court, it shall be the sole responsibility of the respective bus operator to ensure that such fare is in compliance with the law/order/judgment, and WAYBUS shall in no way be liable for such contravention of the law/order/judgment.
                    </Text>
                    <Text style={styles.grayContent}>
                      3. In light of the foregoing, You agree that any liability in relation to any services being offered on the Website in accordance with the applicable laws shall be that of the bus operator and not WAYBUS. In case of any deficiency of service, You agree to pursue any such action arising from such deficiency of service against the bus operator and not the WAYBUS.
                    </Text>
                    <Text style={styles.grayContent}>
                      4. You further agree and acknowledge that the WAYBUS is only a facilitator and is not and cannot be a party to or control in any manner any transactions on the Website. Accordingly, the contract of sale of services on the Website shall be a strictly bipartite contract between You and the bus operators listed on the Website.
                    </Text>
                    <Text style={styles.grayContent}>
                      5. You further agree and acknowledge that all the 'discounts/coupons (if any)' on the Website/prices at which the tickets are being sold by the bus operator on the Website is merely an “invitation to offer” in accordance with the applicable law and shall not be construed to be an “offer” in accordance with the applicable law. Hence, in light of the foregoing, when you agree to purchase the bus tickets listed on the Website by the bus operator, that would be termed as a 'valid offer' under the applicable law Subsequently, when the same is being confirmed by the bus operator it tantamount to be a 'valid contract' as per the applicable law.
                    </Text>        
                  </View>

                  <Text style={styles.blackContent}>
                    3. User Account:
                  </Text>
                  <Text style={styles.grayContent}>
                    WAYBUS may offer You the facility of opening user account on the Website. This user account can be linked to the Your email-id or phone number or both. For Your use of the Website, either by registering an account with WAYBUS or using the Website as a guest (unregistered user), You agree to the following:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. You are solely responsible for maintaining the confidentiality of Your account and password and for restricting access to Your device to prevent unauthorized access to Your account when You use the Website by registering an account with WAYBUS.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. By using the Website, either as a guest user or registered user, You authorize way bus and its agents to access third party sites, including but not limited to that of banks and other payment gateways, designated by the bank or on the bank's behalf for retrieving requested information for processing of a customer generated transaction on the Website.
                    </Text>
                    <Text style={styles.grayContent}>
                      3. In the event that You use the Website through a registered account, You agree to accept responsibility for all activities that occur through your WAYBUS account.
                    </Text>
                    <Text style={styles.grayContent}>
                      4. In the event that You use the Website through a registered account, You should take all necessary steps to ensure that the password is kept confidential and secure and should inform WAYBUS immediately if You have any reason to believe that Your password has been compromised, or if the password is being, or is likely to be, used in an unauthorized manner. WAYBUS shall not be liable for any losses You may incur owing to any compromised login credentials of Your WAYBUS account. Please ensure that the details You provide WAYBUS are correct, complete and up to date and inform WAYBUS immediately of any changes to the information that You provide at the time of registering Your account with WAYBUS.
                    </Text>
                    <Text style={styles.grayContent}>
                      5. WAYBUS will not be responsible for screening, censoring or otherwise controlling transactions, including ascertaining whether the transaction is legal and valid as per the laws of the land, if you are resident/national of a country other than India.
                    </Text>
                    <Text style={styles.grayContent}>
                      6. You warrant that You will abide by all such additional procedures and guidelines, as modified from time to time, in connection with Your use of Website. You shall also be liable to comply with all applicable laws and regulations regarding use of the Website with respect to the jurisdiction concerned for each transaction.
                    </Text>
                    <Text style={styles.grayContent}>
                      7. Website may be used for Your personal and non-commercial purposes only. Therefore, You are not allowed to re-sell, deep-link, use, copy, monitor (e.g. spider, scrape), display, download or reproduce any content or information, software, products or Facility available on Website for any commercial or competitive activity/purpose.
                    </Text>
                    <Text style={styles.grayContent}>
                      8. WAYBUS reserves the right to refuse Your access to Website, terminate Your WAYBUS account, cancel any bus ticket reservations, remove and/or edit content on the Website at any time without notice if we have reasonable belief that Your account is being used for purposes other than as defined under Clause 3(7).
                    </Text>
                  </View>  

                  <Text style={styles.blackContent}>
                    4. Membership Eligibility:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. Use of the Website is available only to persons who can enter into legally binding contracts under the applicable law. Persons who are "incompetent to contract" within the meaning of the applicable law are not eligible to use the Website. If You are a minor, you shall not register as a User of the Website and shall not transact on or use the Website.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. As a minor if You wish to use or transact on the Website, such use or transaction may be made by Your legal guardian or parents. We reserve the right to terminate Your membership and/or refuse to provide You with access to the Website if it is discovered that You are a minor or incompetent to contract according to the law.
                    </Text>
                  </View>
                  
                  <Text style={styles.blackContent}>
                    5. WAYBUS Wallet:
                  </Text>
                  <Text style={styles.grayContent}>
                    WAYBUS may provide at its sole discretion, the facility to transact through an online way bus wallet ("Wallet") to its registered users with the following features:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. Upon cancellation of previously booked tickets, you would be accorded an option of either withdrawing such amounts to your bank account/credit card linked to the account or to the Wallet.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. The cash equivalent balance available in the Wallet may be used by the Customer for making bus ticket bookings or avail any other services available at www.waybus.in (Website) and WAYBUS Mobile Application only.
                    </Text>
                    <Text style={styles.grayContent}>
                      3. The present form and format of the Wallet, issued by way bus to its Customers, is modelled on a closed system prepaid payment instrument.
                    </Text>
                    <Text style={styles.grayContent}>
                      4. Any promotional cash credited in to your Wallet by way bus, will not be refundable into your bank account under any circumstances. On cancellation of a reservation of services provided by WAYBUS, any utilised promotional cash will be forfeited. This promotional cash has an expiry date beyond which, it will not be available for your usage.
                    </Text>
                    <Text style={styles.grayContent}>
                      5. The customers are advised to use the amount lying in the Wallet within its validity period. Any amount lying unutilised (except promotional cash deposited by WAYBUS) beyond a period of three hundred and sixty-five days shall be deemed to be held in trust with the Company. It will be held in trust for a maximum period of one year, after which WAYBUS will make reasonable efforts to transfer such amount to the beneficiary and if such transfer is not an option, any unclaimed amount will be forfeited.
                    </Text>
                    <Text style={styles.grayContent}>
                      6. Maximum of 10% of the ticket price can be availed from the wallet promotional cash for ticket booking. WAYBUS reserves the right to modify such percentage at its sole discretion without any prior intimation.
                    </Text>
                    <Text style={styles.grayContent}>
                      7. The amount lying in the Wallet are not transferable to any other Wallet of same or different user.
                    </Text>
                    <Text style={styles.grayContent}>
                      8. The option of keeping the refund amount in Wallet is available only to resident Indians only. Also the amount lying in the Wallets are not available for transactions in foreign currency.
                    </Text>
                    <Text style={styles.grayContent}>
                      9. By choosing the option to maintain the Wallet with the Company, you agree to comply with the aforesaid terms and conditions.
                    </Text>
                    <Text style={styles.grayContent}>
                      10. The Company reserves the right to suspend/discontinue Wallet scheme to customers at any time, for any cause, including, but not limited to, for any violation of the Terms and Conditions mentioned herein by the Wallet user or to comply with any rules, regulations, orders, directions, notifications issued by any regulatory authority.
                    </Text>
                    <Text style={styles.grayContent}>
                      11. The Company makes no express or implied warranty, guarantee, representation or undertaking whatsoever regarding the Services, which are not expressly mentioned herein.
                    </Text>
                    <Text style={styles.grayContent}>
                      12. The Company may at its sole discretion change, by addition or deletion, these Terms and Conditions.
                    </Text>
                  </View>  

                  <Text style={styles.blackContent}>
                    6. Privacy:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. The Company may at its sole discretion change, by addition or deletion, these Terms and Conditions.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. The 'Cookie Policy' of Website.
                    </Text>
                  </View>  

                  <Text style={styles.blackContent}>
                    7. Links:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. This Website may contain links to other websites maintained by third parties ("External Sites"). These External Sites are linked to the Website for Your reference and convenience only. WAYBUS does not operate, control or endorse in any respect such External Sites or their content. You assume sole responsibility for use of these External Sites and is therefore, advised to examine the terms and conditions of those External Sites carefully.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. You must not link Your own website or any third party website, to this Website without obtaining the prior written approval of WAYBUS. Use of any automated screen capture or screen scraping technologies to obtain information from this Website without the prior written approval of WAYBUS is an infringement of our intellectual property rights.
                    </Text>
                  </View>  

                  <Text style={styles.blackContent}>
                    8. Usage Conduct:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. You acknowledge that You only have a limited right to use the Website and that You have no right to modify any part of the Website or reproduce, copy, distribute, sell, resell or access the Facility for any commercial purposes.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. You are also under an obligation to use this Website for reasonable and lawful purposes only, and shall not indulge in any activity that is not envisaged in these Terms. You shall use this Website, and any bus tickets purchased through it, for personal, non-commercial use only and shall not re-sell the tickets to any other person.
                    </Text>
                    <Text style={styles.grayContent}>
                      3. You may not use any meta tags or any other hidden text utilizing the Website or its affiliates' names or trademarks without the express written consent of WAYBUS and or its affiliates, as applicable.
                    </Text>
                    <Text style={styles.grayContent}>
                      4. You must not use the Website for any of the following:
                    </Text>

                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        1. for fraudulent purposes, or in connection with any criminal acts or other unlawful activity; and/or
                      </Text>
                      <Text style={styles.grayContent}>
                        2. to send or transport in the carriage of the bus, any material that does not belong to You; or material that is illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libellous, obscene, pornographic, paedophilic or menacing; ethnically objectionable, disparaging or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or relates to or promotes money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, security or sovereignty of India or friendly relations with foreign States; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam” to cause annoyance, inconvenience or needless anxiety.
                      </Text>
                    </View> 
                  </View>  

                  <Text style={styles.blackContent}>
                    9. Correspondence/Notices:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. When You use the Website or send emails or other data, information or communication to WAYBUS, You agree and understand that You are communicating with us through electronic records and You consent to receive communications via electronic means from way bus periodically and as and when required.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. We may communicate with You through email/SMS or by such other mode of communication, electronic or otherwise.
                    </Text>
                  </View>  

                  <Text style={styles.blackContent}>
                    10. Disclaimer of Warranties and Liability:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. This Website, all the services (including but not limited to software) included on or otherwise made available to You through this Website are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing by WAYBUS or on the Website.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. Without prejudice to the forgoing paragraph, Website does not warrant that:
                    </Text>
                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        1. Website will be constantly available, or available at all; or
                      </Text>
                      <Text style={styles.grayContent}>
                        2. The information on this Website is complete, true, accurate or non-misleading.
                      </Text>
                    </View>  
                    
                    <Text style={styles.grayContent}>
                      3. WAYBUS will not be liable to You in any way or in relation to the contents of, or use of, or otherwise in connection with, the Website. wherever, the same is under the control of the bus operator. The Website does not warrant that this Website; information, content, materials, product (including software) Facility or services included on or otherwise made available to You through the Website; the servers; or electronic communication sent from us are free of viruses or other harmful components, despite our best efforts to prevent these incidents.
                    </Text>
                    <Text style={styles.grayContent}>
                      4. You are required to enter a valid phone number while booking a bus ticket on the Website. By registering Your phone number with us, You consent to be contacted by us for the purposes of the transaction on the Website or for sending you promotional offers or content.
                    </Text>
                    <Text style={styles.grayContent}>
                      5. For the purpose of booking bus tickets through the Website, we warrant that we shall be responsible for the following activities:
                    </Text>

                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        1. Issuing a valid ticket (a ticket that will be accepted by the bus operator); and
                      </Text>
                      <Text style={styles.grayContent}>
                        2. Providing customer support and information in case of any delays in the departure of a bus / inconvenience caused to You.
                      </Text>
                      <Text style={styles.grayContent}>
                        3. WAYBUS will process the ticket cancellation request from customers subject to the cancellation and refund policy of the respective bus operator. The cancellation fee may differ for each bus operator.
                      </Text>
                      <Text style={styles.blackContent}>
                        However, We DO NOT take any liability for the following:
                      </Text>
                      <Text style={styles.grayContent}>
                        1. The bus operator's bus not departing from/reaching the pick-up point or destination on time;
                      </Text>
                      <Text style={styles.grayContent}>
                        2. The bus operator's employee/s being rude to You;
                      </Text>
                      <Text style={styles.grayContent}>
                        3. The bus operator's bus seats or the journey not being up to Your expectation;
                      </Text>
                      <Text style={styles.grayContent}>
                        4. The bus operator modifying and/or cancelling your bus ticket reservation partially or completely due to unavoidable reasons as described in the following clauses;
                      </Text>
                      <Text style={styles.grayContent}>
                        5. Your baggage getting lost/stolen/damaged;
                      </Text>
                      <Text style={styles.grayContent}>
                        6. The bus operator changing a customer's seat at the last minute to accommodate a female / child passenger;
                      </Text>
                      <Text style={styles.grayContent}>
                        7. Bus departing without You boarding the bus, while You were waiting at the wrong boarding point (please call the bus operator to find out the exact boarding point if you are not a regular traveller of a particular bus operator);
                      </Text>
                      <Text style={styles.grayContent}>
                        8. The bus operator changing the boarding point and/or using a pick-up vehicle at the boarding point to take the passengers to the bus departure point; and
                      </Text>
                      <Text style={styles.grayContent}>
                        9. The bus operator not permitting Your baggage beyond a limit determined at the bus operator’s sole discretion.
                      </Text>
                    </View>  
                  </View>  

                  <Text style={styles.blackContent}>
                    11. Payment:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. By the use of any of the payment method/s available on the Website by You, WAYBUS shall not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to any of the following:
                    </Text>
                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        1. Lack of authorization for any transaction/s; or
                      </Text>
                      <Text style={styles.grayContent}>
                        2. Exceeding the preset limit mutually agreed by You and any bank/s; or
                      </Text>
                      <Text style={styles.grayContent}>
                        3. Any payment issues arising out of the transaction; or
                      </Text>
                      <Text style={styles.grayContent}>
                        4. Decline of transaction for any other reason/s.
                      </Text>
                    </View>  

                    <Text style={styles.grayContent}>
                      2. Please note that:
                    </Text>
                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        1. Transactions, transaction price and all commercial terms governing the provision of services are bipartite contractual obligations between You and the bus operator. way bus acts merely as a facilitator being an independent platform and at no point in time, enters into any direct /contractual arrangement with the customers with regard to the services provided by the bus operator. Use of the payment Facility shall not render way bus liable or responsible for the non-delivery, non-receipt, non-payment, damage, breach of representations and warranties, or fraud as regards the services listed on the Website.
                      </Text>
                      <Text style={styles.grayContent}>
                        2. You have specifically authorized the Website or its service providers to collect, process, facilitate and remit payments and/or the transaction price electronically. Your relationship with Website is on a principal to principal basis and by accepting these Terms You agree that Website is an independent contractor for all purposes, and does not have control of or liability for the products or services that are listed on the Website that are paid for by using the payment facility.
                      </Text>
                      <Text style={styles.grayContent}>
                        3. You understand, accept and agree that the payment facility provided through any third party on the Website is neither a banking nor financial service provided by way bus, but is merely a facilitator providing an electronic, automated online electronic payment collection and remittance facility for the Transactions on the Website using the existing authorized banking infrastructure and credit card payment gateway networks. Further, by providing payment facility Website is neither acting as a trustee nor acting in a fiduciary capacity with respect to the transaction or the transaction price.
                      </Text>
                    </View>
                  </View>

                  <Text style={styles.blackContent}>
                    12. Cancellation & Refund Policy:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.blackContent}>
                      1. Cancellation policy
                    </Text>
                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        WAYBUS will process the ticket cancellation request from You as per the cancellation/refund policy of the bus operator. The cancellation fee and the period taken to process the refund will differ for each bus operator. Please refer to the bus operator's cancellation policy.
                      </Text>
                    </View> 

                    <Text style={styles.blackContent}>
                      2. How does the customer cancel a ticket?
                    </Text>
                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        Please call on +91-8095858592 for all cancellation related queries. Our customer support team will help you process the request as per the cancellation policy of the bus operator.
                      </Text>
                    </View> 

                    <Text style={styles.blackContent}>
                      3. Refund Policy
                    </Text>
                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        1. Customer will be entitled to a 100% refund of ticket fare if the cancellation of the journey is attributable to either WAYBUS or the bus operator. Customer will not be entitled to refund for cancellation of tickets for any other reasons.
                      </Text>
                      <Text style={styles.grayContent}>
                        2. In the event of dishonour of ticket by the bus operator, a full refund of the ticket fare would be processed within seventy two (72) hours. The refund would be credited to the customer within seven (7) working days of the dishonour of ticket.
                      </Text>
                    </View>  
                  </View> 

                  <Text style={styles.blackContent}>
                    13. Carriage Policy:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. You are responsible for ensuring that Your travel date, time and destination are correct before booking/reserving the bus tickets or when you select to confirm your ticket purchase on the Website. Please check the cancellation Policy available on the Website for details about cancellation and refunds.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. You are solely responsible to be at the designated boarding point reasonably in advance before departure time. We are not liable if you fail to board the bus by the time the bus departs.
                    </Text>
                    <Text style={styles.grayContent}>
                      3. The bus operators reserve the right to refuse you and your luggage from carriage on the bus for whatsoever reason that they deem justified, including but not limited to:
                    </Text>

                    <View style={styles.leftSpacing}>
                      <Text style={styles.grayContent}>
                        1. Carrying of contraband, illegal substances, fragile or oversize/overweight luggage, Your unruly behavior, drunkenness or any other behavior that the bus operator deems to affect the other passengers' comfort or safety.
                      </Text>
                      <Text style={styles.grayContent}>
                        2. You are unable to produce valid government issued identification proof while travelling.
                      </Text>
                      <Text style={styles.grayContent}>
                        3. The payment of Your fare for the ticket is fraudulent;
                      </Text>
                      <Text style={styles.grayContent}>
                        4. The booking of Your seat has been done fraudulently or unlawfully or has been purchased from a person not authorized by WAYBUS;
                      </Text>
                      <Text style={styles.grayContent}>
                        5. The credit card through which your payment was made for the ticket booking has been reported lost or stolen;
                      </Text>
                      <Text style={styles.grayContent}>
                        6. The itinerary or booking or confirmation slip is counterfeit or fraudulently obtained;
                      </Text>
                      <Text style={styles.grayContent}>
                        7. The itinerary of your reservation has been altered by a person other than WAYBUS or our authorized agent on your express instructions;
                      </Text>
                      <Text style={styles.grayContent}>
                        8. You are unable to produce a valid and legible boarding ticket for the intended travel. The boarding ticket constitutes as the prima facie evidence of the contract of carriage between the bus operator and the boarding ticket holder;
                      </Text>
                      <Text style={styles.grayContent}>
                        9. You are deemed medically unfit to travel and may pose a health hazard to other passengers on board the bus, at the absolute discretion of the bus operator;
                      </Text>
                      <Text style={styles.grayContent}>
                        10. You fail to arrive on time to board before the time of departure or fail to board the bus by the time the bus departs.
                      </Text>
                      <Text style={styles.grayContent}>
                        11. If the bus operator has refused to carry You or choose to remove You from carriage as per the reasons abovementioned, we reserve the right to cancel the unused ticket and You will not be entitled to further carriage or refund of fare. We will not be liable for the consequential or incidental loss, damage, cost, or fee You may incur due to the refusal of carriage.
                      </Text>
                    </View>

                    <Text style={styles.grayContent}>
                      4. Children below age twelve (12) will not be allowed to book tickets for themselves nor will be allowed to travel, unless they are accompanied by an adult.
                    </Text>  
                    <Text style={styles.grayContent}>
                      5. Children above the age of 5 years need to compulsorily obtain a bus ticket at the regular fare of the ticket, unless otherwise a particular bus operator specifies otherwise in their terms and conditions.
                    </Text>
                    <Text style={styles.grayContent}>
                      6. The bus operator reserve the right to reschedule, cancel, and/or delay any journey and substitute other buses for reasons they deem necessary to do so.
                    </Text>
                    <Text style={styles.grayContent}>
                      7. You are responsible to ensure that valid and necessary government issued personal identification documents, such as the passport, PAN card or Aadhar card, are carried with you for the journey.
                    </Text>  
                  </View>

                  <Text style={styles.blackContent}>
                    14. Intellectual Property Rights:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. Content included on the Website, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software, is the property of WAYBUS, its affiliates or its content suppliers and is protected by Indian and international copyright and database right laws.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. The compilation of all content on this Website is the exclusive property of Website and its affiliates and is protected by laws of India and international copyright and database right laws. All software used on this Website is the property of WAYBUS, its affiliates or its software suppliers and is protected by Indian and international copyright and authors' rights laws.
                    </Text> 
                    <Text style={styles.grayContent}>
                      3. You may not systematically extract/or re-utilise any parts of the contents of the Website without our express written consent. In particular, You may not utilize any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation of any substantial parts of this Website, without WAYBUS's express written consent. You may also not create and/or publish Your own database that features substantial (eg: prices and service listings) parts of the Website without Rebus's express written consent.
                    </Text>  
                    <Text style={styles.grayContent}>
                      4. You cannot use the WAYBUS trademarks for commercially exploiting them for Your interests without our express permission. We reserve the right to initiate legal proceedings if we discover any infringement of our intellectual property rights.
                    </Text> 
                  </View>
                  
                  <Text style={styles.blackContent}>
                    15. Grievance Officer:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      In case of any consumer grievance, the End-User may contact WAYBUS on the email id provided below:
                    </Text>
                    <Text style={styles.grayContent}>
                      support@waybus.in
                    </Text>
                  </View> 

                  <Text style={styles.blackContent}>
                    16. Indemnity:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. You shall indemnify and hold harmless WAYBUS, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of these Terms or any document incorporated by reference, or Your violation of any law, rules, regulations or the rights of a third party.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. You hereby expressly release WAYBUS or any of its affiliates or officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the vendors and specifically waiver any claims or demands that you may have in this behalf under any statute, contract or otherwise.
                    </Text>
                  </View>     

                  <Text style={styles.blackContent}>
                    17. Losses:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      WAYBUS will not be responsible for any loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) and any other indirect or consequential loss to You when You commenced using the Website.
                    </Text>
                  </View> 

                  <Text style={styles.blackContent}>
                    18. Governing law and Jurisdiction:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      These Terms are governed by and shall be construed in accordance with the laws of India. The courts in Bengaluru shall have exclusive jurisdiction in respect of any disputes arising out of or in connection with these Terms.
                    </Text>
                  </View> 

                  <Text style={styles.blackContent}>
                    19. Suspension, Termination or Cancellation
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      Website may suspend, cancel or terminate Your account registered with us, with or without prior notice, if we believe in good faith that You have breached any of these Terms or any other terms or policies referred to in these Terms.
                    </Text>
                    <Text style={styles.grayContent}>
                      WAYBUS reserves the right, at its sole discretion, to accept, hold and/or cancel any reservation of bus tickets made by the You on the WAYBUS website, WAYBUS mobile website and WAYBUS mobile apps, which is deemed to be fraudulent or suspicious by WAYBUS.
                    </Text>
                    <Text style={styles.grayContent}>
                      WAYBUS will endeavour to inform You in the event of cancellation of reservation, owing to fraud or suspicious activity, to the best of its capacity, but shall not be liable for a failure to communicate to You of such cancellation.
                    </Text>
                  </View>  

                  <Text style={styles.blackContent}>
                    20. Amendment / Modification:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      WAYBUS reserves the right to modify these Terms at any time with or without any further notice by uploading the revised Terms on the Website and it is Your duty to keep yourself aware of the revisions to the Terms of the Website.
                    </Text>
                  </View> 

                  <Text style={styles.blackContent}>
                    21. Limitation Of Liability:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      THE WEBSITE/WAYBUS WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, ARISING OUT OF OR IN CONNECTION WITH THE TERMS, SITE, FACILITY, TRANSACTION PROCESSING SERVICE, INABILITY TO USE THE FACILITY OR THE TRANSACTION PROCESSING SERVICE, OR THOSE RESULTING FROM ANY FACILITY PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH THE WEBSITE, BEYOND THE VALUE OF THE LAST TRANSACTION CARRIED OUT BY YOU THROUGH THE WEBSITE.
                    </Text>
                  </View> 

                  <Text style={styles.blackContent}>
                    22. Miscellaneous:
                  </Text>
                  <View style={styles.leftSpacing}>
                    <Text style={styles.grayContent}>
                      1. The Parties acknowledge and accept that electronic format shall be deemed an acceptable means of communication for the purposes of these Terms.
                    </Text>
                    <Text style={styles.grayContent}>
                      2. These Terms constitute the complete and entire set of terms between the Parties on the subject of ‘terms of usage of the Website' (save and except the other policies and terms referred to in these Terms) and shall supersede any and all other prior understandings, commitments, representations or agreements, whether written or oral, between the Parties to these Terms.
                    </Text>
                    <Text style={styles.grayContent}>
                      3. If any provision of these Terms shall be found by any court or administrative body of competent jurisdiction to be invalid or unenforceable, such invalidity or enforceability shall not affect the other provisions of these Terms, which shall remain in full force and effect.If any provision of these Terms shall be found by any court or administrative body of competent jurisdiction to be invalid or unenforceable, such invalidity or enforceability shall not affect the other provisions of these Terms, which shall remain in full force and effect.
                    </Text>
                    <Text style={styles.grayContent}>
                      4. In no event will any delay, failure or omission (in whole or in part) in enforcing, exercising or pursuing any right, power, privilege, claim or remedy conferred by or arising under these Terms or by law, be deemed to be or construed as a waiver of that or any other right, so as to bar the enforcement of that, or any other right, power privilege, claim or remedy, in any other instance at any time or times subsequently.
                    </Text>
                  </View> 

                  <Text style={[styles.blackContent, {marginBottom:100}]}>
                    PLEASE BE AWARE THAT BY DISPLAYING INFORMATION ABOUT A SERVICE PROVIDER, WAYBUS IS NOT SUGGESTING THAT, AVAILING THEIR SERVICES IS ADVISABLE OR RISK FREE. WAYBUS IS NOT LIABLE FOR ANY DAMAGES AND/OR LOSSES THAT MAY RESULT FROM THE CUSTOMER DECIDING TO AVAIL SUCH SERVICES. ANY SUCH RESERVATION MADE BY THE CUSTOMER IS AT THE CUSTOMER’S SOLE RISK BASIS THE CUSTOMER’S INDEPENDENT JUDGEMENT.
                  </Text>

                </View>   

              )}
                keyExtractor = {item=> {item}}
            />

          </View>   
        </View>
      </View>
    );
  }
}
